config/routes.rb
Rails.application.routes.draw do

  root to: 'static_pages#home'
  get 'signup',  to: 'users#new'
  get    'login' , to: 'sessions#new'
  post   'login' , to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  resources :users do
    member do
      get 'followings'
      get 'followers'
      get 'favoriteposts'
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts
  resources :relationships, only: [:create, :destroy]
  resources :favoritepost_relationships, only: [:create, :destroy]
  resources :repost_relationships, only: [:create, :destroy]

end

app/models/user.rb
class User < ActiveRecord::Base
  before_save { self.email = email.downcase }
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  validates :biography, length: { maximum: 100 }
  validates :location, length: { maximum: 100 }
  
  has_secure_password
  
  has_many :microposts
  
  has_many :following_relationships, class_name:  "Relationship",
                                     foreign_key: "follower_id",
                                     dependent:   :destroy
  has_many :following_users, through: :following_relationships, source: :followed
  
  has_many :follower_relationships, class_name:  "Relationship",
                                    foreign_key: "followed_id",
                                    dependent:   :destroy
  has_many :follower_users, through: :follower_relationships, source: :follower
  
  # 他のユーザーをフォローする
  def follow(other_user)
    following_relationships.find_or_create_by(followed_id: other_user.id)
  end

  # フォローしているユーザーをアンフォローする
  def unfollow(other_user)
    following_relationship = following_relationships.find_by(followed_id: other_user.id)
    following_relationship.destroy if following_relationship
  end

  # あるユーザーをフォローしているかどうか？
  def following?(other_user)
    following_users.include?(other_user)
  end
  
  def feed_items
    Micropost.where(user_id: following_user_ids + [self.id])
  end
  
  #
  # お気に入り機能で使用する
  #
  has_many :favoritepost_relationships , class_name:  "FavoritepostRelationship",
                                        foreign_key: "user_id",
                                        dependent: :destroy
  has_many :favoriteposts, through: :favoritepost_relationships, source: :micropost
  # あるツイートをお気に入りにする
  def regist_favoritepost(micropost)
    favoritepost_relationships.find_or_create_by(micropost_id: micropost.id)
  end
  
  # あるツイートをお気に入りから外す
  def release_favoritepost(micropost)
    favoritepost_relationship = favoritepost_relationships.find_by(micropost_id: micropost.id)
    favoritepost_relationship.destroy if favoritepost_relationship
  end
  
  # あるツイートをお気に入りにしているかどうか？
  def is_favoritepost?(micropost)
    favoriteposts.include?(micropost)
  end
  
  #
  # リツイート機能で使用する
  #
  # このユーザが指定されたツイートをリツイートした時の関連を取得する
  def get_repost_relationship(micropost)
    if !micropost.reposted_posts.any?
      return nil
    end
    
    posting = micropost.reposted_posts.find_by(user_id: self.id)
    
    if posting.blank?
      return nil
    end
    
    return posting.reposting_relationship
  end
  

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:edit, :update]
  
  def index
    # Userを全て取得する。
    @users = User.all
    @user = current_user
  end

  def show
    @user = User.find(params[:id])
    @microposts = @user.microposts.order(created_at: :desc).page(params[:page])
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = t('users.create_success')
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
    if @user != current_user
      # ログイン中のユーザではないユーザ情報を編集しようとしているので
      # ホーム画面へリダイレクト
      flash[:danger] = "Invalid operation detected!"
      redirect_to root_url
    end
  end
  
  def update
    #binding.pry
    
    if @user != current_user
      # ログイン中のユーザではないユーザ情報を行進しようとしているので
      # ホーム画面へリダイレクト
      flash[:danger] = "Invalid operation detected!"
      redirect_to root_url
    end
    
    # 更新時のhas_secure_passwordは、
    # フォームから入力されたパスワードが空でも、エラーにならず、
    # DBのパスワードダイジェスト情報が空になることはない
    if @user.update(user_params)
      # 保存に成功した場合はユーザ画面へリダイレクト
      flash[:success] = t('users.edit_success')
      redirect_to @user
    else
      # 保存に失敗した場合は編集画面へ戻す
      render 'edit'
    end
  end
  
  def followings
    @user = User.find(params[:id])
    @following_users = @user.following_users
  end
  
  def followers
    @user = User.find(params[:id])
    @followed_users = @user.follower_users
  end
  
  def favoriteposts
    @user = User.find(params[:id])
    @microposts = @user.favoriteposts.order(created_at: :desc).page(params[:page])
  end
  
  private

  def user_params
    params.require(:user).permit(:name, :email, :password,
                                 :password_confirmation,
                                 :biography, :location, :birthday)
  end
  
  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/users/_follow.html.erb
<%= form_for(current_user.following_relationships.build, remote: true) do |f| %>
  <div><%= hidden_field_tag :followed_id, follow_user.id %></div>
  <%= f.submit t('users.follow'), class: "btn btn-primary" %>
<% end %>

app/views/users/_follow_form.html.erb
<% if current_user != @user %>
  <div id="<%= "follow_form" + @user.id.to_s %>">
  <% if current_user.following?(@user) %>
    <%= render partial: 'unfollow', locals: { unfollow_user: @user } %>
  <% else %>
    <%= render partial: 'follow', locals: { follow_user: @user } %>
  <% end %>
  </div>
<% end %>

app/views/users/_relational_user.html.erb
<div id="relational_user-<%= relational_user.id %>" class="col-md-4">
  <div class="media">
    <%= link_to gravatar_for(relational_user, size: 50), relational_user, class: "media-left" %>
  	<div class="media-body">
      <span class="user"><%= link_to relational_user.name, relational_user %></span>
      <% #他人のフォロー・フォロワー一覧内の自分はフォローできないようにする. %>
      <% if relational_user != current_user %>
        <div id="<%= "follow_form" + relational_user.id.to_s %>" class="follow-unfollow-button">
          <% if current_user.following?(relational_user) %>
            <%= render partial: 'unfollow', locals: { unfollow_user: relational_user } %>
          <% else %>
            <%= render partial: 'follow', locals: { follow_user: relational_user } %>
          <% end %>
        </div>
  	  <% end %>
  	</div>
  </div>
</div>

<!--
BootStrap の media を使わないと、画面が小さい時に綺麗に縦に並べる方法が難しかった。
<div id="relational_user-<%#= relational_user.id %>" class="col-md-4 ">
  <%#= link_to gravatar_for(relational_user, size: 50), relational_user %>
  <span class="user"><#%= link_to relational_user.name, relational_user %></span>
</div>
-->

app/views/users/_relational_users.html.erb
<div class="relational_users">
  <% #ユーザは３人ごとに横に並べる %>
  <div class="row">
  <% column_num = 3 %>
    <% relational_users.each_with_index do |relational_user, i| %>
      <% #あるユーザの情報を記述する %>
      <%= render partial: 'relational_user',
        locals: { relational_user: relational_user } %>
      
      <% if i % column_num + 1 == column_num %>
        </div>
        <div class="row">
      <% end %>
    <% end %>
  </div>
</div>

app/views/users/_sidebar_user.html.erb
<section class="user_info">
  <h1>
    <%= gravatar_for @user %>
    <%= @user.name %>
  </h1>
  <h3>
    <%= @user.biography %>
  </h3>
</section>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.following_relationships.find_by(followed_id: unfollow_user.id),
             html: { method: :delete },
             remote: true) do |f| %>
  <%= f.submit t('users.unfollow'), class: "btn" %>
<% end %>

app/views/users/edit.html.erb
<h1><%= t('.title') %></h1>

<div class="row">
  <div class="col-md-8 col-md-offset-2">
    
    <%= form_for(@user, html: {class: 'form-horizontal'}) do |f| %>
    
      <%= render 'shared/error_messages', object: f.object %>
    
      <div class="form-group">
        <%= f.label :name, t('.name'), class: "col-md-2 control-label" %>
        <div class="col-md-6">
          <%= f.text_field :name, class: "form-control" %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :email, t('.email'), class: "col-md-2 control-label" %>
        <div class="col-md-6">
          <%= f.text_field :email, class: "form-control" %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :password, t('.password'), class: "col-md-2 control-label" %>
        <div class="col-md-6">
          <%= f.password_field :password, class: "form-control" %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :password_confirmation,
          t('.password_confirmation'), class: "col-md-2 control-label" %>
        <div class="col-md-6">
          <%= f.password_field :password_confirmation, class: "form-control" %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :biography, t('.biography'), class: "col-md-2 control-label" %>
        <div class="col-md-10">
          <%= f.text_field :biography, class: "form-control" %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :location, t('.location'), class: "col-md-2 control-label" %>
        <div class="col-md-10">
          <%= f.text_field :location, class: "form-control" %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :birthday, t('.birthday'), class: "col-md-2 control-label" %>
        <div class="col-md-10">
          <%= f.date_select :birthday, { start_year: 1900, include_blank: true },
            { class: "form-control bootstrap-date" } %>
        </div>
      </div>
      <div class="form-group">
        <div class="col-md-2 col-md-offset-2">
          <%= f.submit class: "btn btn-large btn-primary" %>
        </div>
      </div>
    <% end %>
    </div>
  </div>
</div>
<p></p>

app/views/users/favoriteposts.html.erb
<div class="row">
  <aside class="col-md-4">
    <%= render 'sidebar_user' %>
    <div class="btn-group-vertical" role="group">
      <%= link_to t('users.following_users'), followings_user_path(@user),
        class: "btn btn-link btn-lg"%>
      <%= link_to t('users.followed_users'), followers_user_path(@user),
        class: "btn btn-link btn-lg"%>
      <button type="button" class="btn btn-info btn-lg active">
        <%= t('users.favorite_posts') %>
      </button>
    </div>
  </aside>
  <% if logged_in? %>
    <div class="col-md-8">
      <h3><%= t('users.favorite_posts') %> (<%= @microposts.count %>)</h3>
      <% if @microposts.any? %>
        <% #ページネーション開始 %>
        <%= page_entries_info @microposts %>
        <ol class="microposts">
          <%= render @microposts %>
        </ol>
        <%= paginate @microposts %>
        <% #ページネーション終了 %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/users/followers.html.erb
<div class="row">
  <aside class="col-md-4">
    <%= render 'sidebar_user' %>
    <div class="btn-group-vertical" role="group">
      <%= link_to t('users.following_users'), followings_user_path(@user),
        class: "btn btn-link btn-lg"%>
      <button type="button" class="btn btn-info btn-lg active">
        <%= t('users.followed_users') %>
      </button>
      <%= link_to t('users.favorite_posts'), favoriteposts_user_path(@user),
        class: "btn btn-link btn-lg"%>
    </div>
  </aside>
  <% if logged_in? %>
    <div class="col-md-8">
      <h3><%= t('users.followed_users') %> (<%= @followed_users.count %>)</h3>
      <% if @followed_users.any? %>
        <%= render partial: 'relational_users',
          locals: { relational_users: @followed_users } %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/users/followings.html.erb
<div class="row">
  <aside class="col-md-4">
    <%= render 'sidebar_user' %>
    <div class="btn-group-vertical" role="group">
      <button type="button" class="btn btn-info btn-lg active">
        <%= t('users.following_users') %>
      </button>
      <%= link_to t('users.followed_users'), followers_user_path(@user),
        class: "btn btn-link btn-lg"%>
      <%= link_to t('users.favorite_posts'), favoriteposts_user_path(@user),
        class: "btn btn-link btn-lg"%>
    </div>
  </aside>
  <% if logged_in? %>
    <div class="col-md-8">
      <h3><%= t('users.following_users') %> (<%= @following_users.count %>)</h3>
      <% if @following_users.any? %>
        <%= render partial: 'relational_users',
          locals: { relational_users: @following_users } %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/users/index.html.erb
<div class="row">
  <aside class="col-md-4">
    <%= render 'sidebar_user' %>
    <div class="btn-group-vertical" role="group">
      <%= link_to t('users.following_users'), followings_user_path(@user),
        class: "btn btn-link btn-lg"%>
      <%= link_to t('users.followed_users'), followers_user_path(@user),
        class: "btn btn-link btn-lg"%>
      <%= link_to t('users.favorite_posts'), favoriteposts_user_path(@user),
        class: "btn btn-link btn-lg"%>
    </div>
    
    <% #テスト用機能 %>
    <% if @user == current_user %>
      <div>
        <p></p><p></p><p></p>
        <%= link_to t('users.all_users'), users_path,
          class: "btn btn-link btn-lg"%>
      </div>
    <% end %>
  </aside>
  <% if logged_in? %>
    <div class="col-md-8">
      <h3><%= t('users.all_users') %> (<%= @users.count %>)</h3>
      <% if @users.any? %>
        <%= render partial: 'relational_users',
          locals: { relational_users: @users } %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/users/new.html.erb
<h1><%= t('.title') %></h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
    
      <%= render 'shared/error_messages', object: f.object %>

      <div class="form-group">
        <%= f.label :name, t('.name'), class: "control-label" %>
        <%= f.text_field :name, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :email, t('.email'), class: "control-label" %>
        <%= f.text_field :email, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :password, t('.password'),
          class: "control-label" %>
        <%= f.password_field :password, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :password_confirmationt, t('.password_confirmation'),
          class: "control-label" %>
        <%= f.password_field :password_confirmation, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.submit t('.create_account'), class: "btn btn-large btn-primary" %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <aside class="col-md-4">
    <%= render 'sidebar_user' %>
    <div class="btn-group-vertical" role="group">
      <%= link_to t('users.following_users'), followings_user_path(@user),
        class: "btn btn-link btn-lg"%>
      <%= link_to t('users.followed_users'), followers_user_path(@user),
        class: "btn btn-link btn-lg"%>
      <%= link_to t('users.favorite_posts'), favoriteposts_user_path(@user),
        class: "btn btn-link btn-lg"%>
    </div>
    <% #テスト用機能 %>
    <% if @user == current_user %>
      <div>
        <p></p><p></p><p></p>
        <%= link_to t('users.all_users'), users_path,
          class: "btn btn-link btn-lg"%>
      </div>
    <% end %>
  </aside>
  <div class="col-md-8">
    <%= render 'follow_form' if logged_in? %>
    <% if @user.microposts.any? %>
      <h3>Microposts (<%= @user.microposts.count %>)</h3>
      <% #ページネーション開始 %>
      <%= page_entries_info @microposts %>
      <ol class="microposts">
        <%= render @microposts %>
      </ol>
      <%= paginate @microposts %>
      <% #ページネーション終了 %>
    <% end %>
  </div>
</div>